import type { FileAsset } from './file-library';

const STANDALONE_FILE_ASSETS: readonly FileAsset[] = Object.freeze([
  {
    id: 'standalone-asset-courseware-pptx',
    name: '函数单调性智能课件.pptx',
    extension: 'PPTX',
    kind: '课件',
    summary: '18 页智能课件，包含概念讲解、例题迁移和分层练习。',
    size: '12.4 MB',
    version: 'v2',
    createdAt: '2026-08-22T10:08:00+08:00',
    createdLabel: '今天 10:08',
    status: '可使用',
    favorite: true,
    reuseCount: 3,
    sharedTargets: [],
    project: { id: 'standalone-project-courseware', title: '生成函数单调性智能课件', context: '高中数学 / 函数的性质 · 教师手动填写', runId: 'run-m4-courseware' },
    canUseAsContext: true,
    canShare: true,
  },
  {
    id: 'standalone-asset-courseware-practice',
    name: '函数单调性分层练习.docx',
    extension: 'DOCX',
    kind: '练习',
    summary: '基础、提高和迁移三层练习，附答案与解析。',
    size: '186 KB',
    version: 'v1',
    createdAt: '2026-08-22T10:06:00+08:00',
    createdLabel: '今天 10:06',
    status: '可使用',
    favorite: false,
    reuseCount: 1,
    sharedTargets: [],
    project: { id: 'standalone-project-courseware', title: '生成函数单调性智能课件', context: '高中数学 / 函数的性质 · 教师手动填写', runId: 'run-m4-courseware' },
    canUseAsContext: true,
    canShare: true,
  },
  {
    id: 'standalone-asset-package-plan',
    name: '函数单元课程方案.docx',
    extension: 'DOCX',
    kind: '教案',
    summary: '函数单元 6 课时课程方案，包含目标、活动和评价安排。',
    size: '242 KB',
    version: 'v1',
    createdAt: '2026-08-21T16:42:00+08:00',
    createdLabel: '昨天 16:42',
    status: '可使用',
    favorite: true,
    reuseCount: 2,
    sharedTargets: [],
    project: { id: 'standalone-project-package', title: '函数单元课程方案包', context: '高中数学 / 函数单元 · 教师手动填写', runId: 'run-m4-course-package' },
    canUseAsContext: true,
    canShare: true,
  },
  {
    id: 'standalone-asset-quiz-paper',
    name: '动量守恒诊断测验.pdf',
    extension: 'PDF',
    kind: '练习',
    summary: '包含 5 道诊断题、教师版答案与逐题解析。',
    size: '1.8 MB',
    version: 'v1',
    createdAt: '2026-08-20T14:20:00+08:00',
    createdLabel: '3 天前',
    status: '可使用',
    favorite: false,
    reuseCount: 0,
    sharedTargets: [],
    project: { id: 'standalone-project-quiz', title: '生成动量守恒诊断测验', context: '高中物理 / 动量守恒 · 教师手动填写' },
    canUseAsContext: true,
    canShare: true,
  },
]);

export function standaloneFileAssets(): readonly FileAsset[] {
  return STANDALONE_FILE_ASSETS.map((asset) => ({ ...asset, project: { ...asset.project } }));
}
